---
title: "Script get benchmark data"
author: "Lou Duron and Victoria Fathi"
output:
  html_document:
    code_folding: show
    toc: TRUE
    toc_float: TRUE
    toc_depth: 4
    theme: paper
    highlight: tango
editor_options: 
  chunk_output_type: console
---

# Benchmark dataset

```{r}
setwd('/home/victoriafathi/Bureau/M2/m2idh/Part_2/') #to modify
library("tidyverse")
library(jsonlite)
```

```{r}
benchmark_set = read_tsv('sets/uniprot-helicaseorganism__EscherichiacolistrainK12ECOLI--.tab')
uniprot_mapping = read_tsv('import/Alias/uniprot_mapping.tsv')
ecocyc_mapping = read_tsv('import/Alias/ecocyc_mapping.tsv')
```

```{r}
head(benchmark_set)
```

# Mapping 
The first step is to keep genes annotated in Uniprot genome annotation of E.coli and annotated id Ecocyc

```{r}
mapping = benchmark_set %>% 
  select(uniprotID=Entry) %>%
  inner_join(uniprot_mapping) %>%
  select(bnumber, uniprotID) %>%
  inner_join(ecocyc_mapping)

dim(mapping)
```


# GoTerm benchmark
```{r}
# GoTerm benchmark
GO_genes_bm = benchmark_set %>% 
  select(uniprotID=Entry, GO="Gene ontology IDs") %>%
  right_join(mapping) %>%
  select(bnumber, GO) %>% 
  separate_rows(GO, sep='; ')%>%
  arrange(bnumber)
length(unique(GO_genes_bm$bnumber))
write_delim(GO_genes_bm, "benchmark_data/GO_bm.tsv", delim='\t')
```

# Interpro Domains 
```{r}
domains_genes_bm = benchmark_set %>% 
  select(uniprotID=Entry, interpro='Cross-reference (InterPro)') %>%
  right_join(uniprot_mapping) %>% # right join to remove those without bnumber
  separate_rows(interpro, sep=';') %>%
  select(bnumber, interpro) %>%
  arrange(bnumber)
length(unique(domains_genes_bm$bnumber))
write_delim(domains_genes_bm, "benchmark_data/interpro_bm.tsv", delim='\t')
```

# Keywords
```{r}
keywords_genes_bm = benchmark_set %>% 
  select(uniprotID=Entry, keyword=Keywords) %>%
  right_join(uniprot_mapping) %>% # right join to remove those without bnumber
  separate_rows(keyword, sep=';') %>%
  select(bnumber, keyword) %>%
  arrange(bnumber)
length(unique(GO_genes_bm$bnumber))
write_delim(keywords_genes_bm, "benchmark_data/keyword_bm.tsv", delim='\t')
```

# TU
```{r}
TU_genes = read_tsv("import/TU/TU_link.tsv")

TU_genes_bm = mapping %>%
  select(bnumber) %>%
  left_join(TU_genes)
length(unique(TU_genes_bm$bnumber))
write_delim(TU_genes_bm, "benchmark_data/TU_bm.tsv", delim='\t')

```


# Pathway
```{r}
Pathway_genes = read_tsv('import/Pathway/pathway_link.tsv')

Pathway_genes_bm = mapping %>%
  select(bnumber) %>%
  left_join(Pathway_genes)
length(unique(Pathway_genes_bm$bnumber))
write_delim(Pathway_genes_bm, "benchmark_data/Pathway_bm.tsv", delim='\t')
```


