---
title: "TP1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(jsonlite)
```


```{r}
uniprot = read_tsv("ecoli/uniprot-proteome_UP000000625.tab")
uniprot
```
```{r}
mapping = uniprot %>% 
  select(Entry, names = `Gene names  (ordered locus )`) %>%
  mutate(bnumber=str_extract(names, 'b\\d+')) %>%
  select(bnumber, uniprotID=Entry) %>%
  filter(!is.na(bnumber)) %>% # 2021 → P0DQD7 and P0A6D5 are lost (no bnumber)
  arrange(bnumber)
mapping
```

```{r}
keywords = uniprot %>% 
  select(uniprotID=Entry, keyword=Keywords) %>%
  right_join(mapping) %>% # right join to remove those without bnumber
  separate_rows(keyword, sep=';') %>%
  select(bnumber, keyword) %>%
  arrange(bnumber)
keywords
```

```{r}
ref_sets = keywords %>% 
  group_by(keyword) %>%
  summarise(count=n(), elements = list(bnumber)) %>%
  ungroup %>%
  filter(count>1)  %>%
  select(id=keyword, desc=count, elements)
ref_sets

ref_sets %>% toJSON %>% write("reference.sets/uniprot.keywords.sets.json")
```




