---
title: "TP1 IDH PART2"
author: "Victoria FATHI"
output:
  html_document:
    code_folding: show
    toc: TRUE
    toc_float: TRUE
    toc_depth: 4
    theme: paper
    highlight: tango
editor_options: 
  chunk_output_type: console
---

```{r}
setwd('/home/victoriafathi/Bureau/M2/m2idh/Part_2/')
library(tidyverse)
library(jsonlite)
```

```{r}
uniprot = read_tsv("ecoli/uniprot-proteome_UP000000625.tab.gz")
head(uniprot)
```

Association du nom des gènes aux protéines (id uniprot)
```{r}
mapping = uniprot %>% 
  select(Entry, names = `Gene names  (ordered locus )`) %>%
  mutate(bnumber=str_extract(names, 'b\\d+')) %>%
  select(bnumber, uniprotID=Entry) %>%
  filter(!is.na(bnumber)) %>% # 2021 → P0DQD7 and P0A6D5 are lost (no bnumber)
  arrange(bnumber)
mapping
```

Associe à chaque nom de gènes tous les keywords qui correspondent aux protéines associés
```{r}
keywords = uniprot %>% 
  select(uniprotID=Entry, keyword=Keywords) %>%
  right_join(mapping) %>% # right join to remove those without bnumber
  separate_rows(keyword, sep=';') %>%
  select(bnumber, keyword) %>%
  arrange(bnumber)
```
Group by par mots clés
```{r}
ref_sets = keywords %>% 
  group_by(keyword) %>%
  summarise(count=n(), elements = list(bnumber)) %>%
  ungroup %>%
  filter(count>1)  %>%
  select(id=keyword, desc=count, elements)

ref_sets
```
```{r}
library(jsonlite)
```

Transformation du format tibble à json
```{r}
ref_sets %>% toJSON %>% write("sets/uniprot.keywords.sets.json")
```

```{r}
colnames(uniprot)
```

#Domaine interpro
```{r}
interpro = uniprot %>% 
  select(uniprotID=Entry, interpro='Cross-reference (InterPro)') %>%
  right_join(mapping) %>% # right join to remove those without bnumber
  separate_rows(interpro, sep=';') %>%
  select(bnumber, interpro) %>%
  arrange(bnumber)
```
Group by par mots clés
```{r}
ref_sets_interpro = interpro %>% 
  group_by(interpro) %>%
  summarise(count=n(), elements = list(bnumber)) %>%
  ungroup %>%
  filter(count>1)  %>%
  select(id=interpro, desc=count, elements)

ref_sets_interpro

ref_sets_interpro %>% toJSON %>% write("sets/uniprot.uniprot.sets.json")
```

```{r}
GO = uniprot %>% 
  select(uniprotID=Entry, GO="Gene ontology IDs") %>%
  right_join(mapping) %>% # right join to remove those without bnumber
  separate_rows(GO, sep=';') %>%
  select(bnumber, GO) %>%
  arrange(bnumber)

ref_sets_GO = GO %>% 
  group_by(GO) %>%
  summarise(count=n(), elements = list(bnumber)) %>%
  ungroup %>%
  filter(count>1)  %>%
  select(id=GO, desc=count, elements)
ref_sets_GO

ref_sets_GO %>% toJSON %>% write("reference.sets/GO.sets.json")
```


```{r}
ecocyc = read_tsv("ecoli/All_instances_of_Genes_in_Escherichia_coli_K-12_substr._MG1655.txt")
```

```{r}
colnames(ecocyc)
```

```{r}
ecocyc_mapping = ecocyc %>% 
  select(Genes, names = `Names`) %>%
  mutate(bnumber=str_extract(names, 'b\\d+')) %>%
  select(bnumber, ecocyc=Genes) %>%
  filter(!is.na(bnumber)) %>% # 2021 → P0DQD7 and P0A6D5 are lost (no bnumber)
  arrange(bnumber)
ecocyc_mapping
```


```{r}
TU = read_tsv("ecoli/all_transcription-units.txt")

TU_per_gene = TU %>% select(Site, names = "Genes of transcription unit") %>%
  mutate(genes=str_extract(names, 'b\\d+')) %>%
  select(genes, Site) %>%
  filter(!is.na(genes)) %>% # 2021 → P0DQD7 and P0A6D5 are lost (no bnumber)
  arrange(genes)

TU_per_gene
```
```{r}
pmids %>% select(PMID) %>% unique %>% write_csv("import/ncbi.pmid.csv")
pmids %>% rename(gene_id = bnumber) %>% write_csv("import/ncbi.pmid.genes.csv")
```


```{r}
pathway = read_tsv("ecoli/All_instances_of_Pathways_in_Escherichia_coli_K-12_substr._MG1655.txt")
```

